#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

backend:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
    

homepage:
    path:      /{_locale}
    defaults:  { _controller: AppBundle:Default:index, _locale: en }
    requirements:
        _locale:  en|pt
    
    
contact:
    path:     /contact
    defaults: { _controller: "AppBundle:Default:contact" }
    methods:  [GET, POST]
    
    
email:
    path:     /email
    defaults: { _controller: "AppBundle:Default:email" }
    methods:  [GET, POST]